site_name: Pathogen NGS 数据分析入门
site_description: '病原微生物高通量测序数据分析手册'
site_author: 'Mark Renton'
site_url: 'https://indexofire.github.io/pathongs'
theme: 'material'
copyright: 'Copyright &copy; 2016 - 2018 HZCDC@Lab'

repo_url: https://github.com/indexofire/pathongs/

# theme: light blue
extra:
  palette:
    primary: 'light blue'

pages:
  - '开始之前': index.md
  - '第一章 背景知识介绍':
    - '01. Linux 安装实例': C01_Linux-and-Script-Language/01_linux-installation.md
    - '02. Linux 基本命令': C01_Linux-and-Script-Language/02_basic-cml.md
    - '03. Linux 软件管理': C01_Linux-and-Script-Language/03_linux-software.md
    - '04. 列处理工具 awk': C01_Linux-and-Script-Language/04_awk.md
    - '05. awk 的扩展 bioawk': C01_Linux-and-Script-Language/05_bioawk.md
    - '06. Python 编程': C01_Linux-and-Script-Language/06_python.md
    - '07. Shell脚本': C01_Linux-and-Script-Language/07_shell.md
    - ‘08. Perl 编程’: C01_Linux-and-Script-Language/08_perl.md
    - '09. R 编程': C01_Linux-and-Script-Language/09_r.md
  - '第二章 产用工具':
    - '01. 公共生物数据库': C02_Common-Utility/01_databases.md
    - '02. Blast 与 Blast+': C02_Common-Utility/02_blast.md
    - '03. 玩转 edirect': C02_Common-Utility/03_edirect.md
    - '04. EMBOSS 工具集': C02_Common-Utility/04_emboss.md
    - '07. MUMmer 工具': C02_Common-Utility/07_mummer.md
    - '08. 国产序列处理神器 SeqKit': C02_Common-Utility/08_seqkit.md
    - '09. Kmer 工具': C02_Common-Utility/09_kmer.md
  - ‘第三章 各类数据文件格式’:
    - '01. fasta': C03_File-Format/01_fasta.md
    - '02. embl': C03_File-Format/02_embl.md
    - '03. plain text': C03_File-Format/03_plain-txt.md
  - '第四章 基因组组装':
    - '01. bwa samtools 流程': C04_Pathogen-Genome-Assembly/01_bwa-samtools-pipeline.md
    - '02. GATK 流程': C04_Pathogen-Genome-Assembly/02_gatk.md
    - '03. 细菌基因组组装': C04_Pathogen-Genome-Assembly/03_bacteria-assembly.md
    - '04. 病毒基因组组装': C04_Pathogen-Genome-Assembly/04_virus-assembly.md
    - '05. Quast 验证': C04_Pathogen-Genome-Assembly/05_quast.md
  - '第五章 基因组比对':
    - '01. bwa 长序列比对': C05_Pathogen-Mapping-Pipeline/01_bwa-long-sequence-mapping.md
  - '第六章 基因组注释':
    - '01. Prokka 快速注释': C06_Genome-Annotation/01_prokka.md
    - '02. 在线注释工具 rast': C06_Genome-Annotation/02_rast.md
    - '03. 注释工具 PGAAP': C06_Genome-Annotation/03_PGAAP.md
    - '04. SNP注释工具 snpEFF': C06_Genome-Annotation/04_snpEFF.md
  - '第七章 Pan和Core基因组分析':
    - '01. Pangenome 概述': C07_PanGenome-and-CoreGenome/01_pangenome.md
    - '02. Get_Homologues 分析': C07_PanGenome-and-CoreGenome/02_get_homologues.md
    - '03. BPGA 分析': C07_PanGenome-and-CoreGenome/03_BPGA.md
    - '04. Roary 分析': C07_PanGenome-and-CoreGenome/04_roary.md
    - '05. panseq 分析': C07_PanGenome-and-CoreGenome/05_panseq.md
    - '06. Gubbins 分析': C07_PanGenome-and-CoreGenome/06_gubbins.md
    - '07. OrthMCL 分析': C07_PanGenome-and-CoreGenome/07_orthmcl.md
    - '08. ITEP 分析': C07_PanGenome-and-CoreGenome/08_ITEP.md
  - '第八章 基因组可视化':
    - '01. igv 查看比对结果': C08_Genome-Visualization/01_igv.md
    - '02. BRIG 细菌比较基因组分析工具': C08_Genome-Visualization/02_BRIG.md
    - '03. circos 工具使用': C08_Genome-Visualization/03_circos.md
  - '第九章 分析平台':
    - '01. 基于 docker 镜像': C09_Analysis-Platform/01_docker.md
    - '02. Galaxy 平台': C09_Analysis-Platform/02_galaxy.md
    - '03. Amazon EC2 云平台': C09_Analysis-Platform/03_amazon.md
    - '04. 其他平台': C09_Analysis-Platform/04_others.md
  - '第十章 重组与种群分析':
    - '01. 病毒重组': C10_Recombination-and-Population-Structure/01_virus-recombination.md
  - '第十一章 常见分析工具':
    - '01. SRST2 短序列比对基因工具': C11_Pathogen-NGS-Application/01_srst2.md
    - '02. 拼接序列管家基因扫描工具 MLST': C11_Pathogen-NGS-Application/02_mlst.md
    - '03. 拼接序列耐药基因扫描工具 Ariba': C11_Pathogen-NGS-Application/03_ariba.md
    - '04. 细菌共线性分析工具 C-Sibelia': C11_Pathogen-NGS-Application/04_csibelia.md
  - '第十二章 Metagenomics 分析':
    - '01. kraken': C12_Metagenomics-Analysis/01_kraken.md
    - '02. centrifuge': C12_Metagenomics-Analysis/02_centrifuge.md
    - '03. bracken': C12_Metagenomics-Analysis/03_bracken.md
    - '04. sourmash': C12_Metagenomics-Analysis/04_sourmash.md
    - '05. clark': C12_Metagenomics-Analysis/05_clark.md
    - '06. krona': C12_Metagenomics-Analysis/06_krona.md
    - '07. pavian': C12_Metagenomics-Analysis/07_pavian.md
    - '08. supri': C12_Metagenomics-Analysis/08_supri.md
    - '10. 16S 种群分析': C12_Metagenomics-Analysis/01_16s.md
  - '第十三章 单分子测序':
    - '01. nanopore': C13_Single-Molecular-Sequencing/01_nanopore.md
    - '02. pacbio': C13_Single-Molecular-Sequencing/02_pacbio.md
    - '03. canu': C13_Single-Molecular-Sequencing/03_canu.md
    - '04. trimming': C13_Single-Molecular-Sequencing/04_trimming.md
    - '06. hybrid': C13_Single-Molecular-Sequencing/06_hybrid.md
  - '第十四章 进化树构建':
    - '01. 多重序列比对': C14_Phylogeny-Analysis/01_msa.md
    - '02. RAxML': C14_Phylogeny-Analysis/02_raxml.md
  - '第十五章 基因组流行病学':
    - '04. CartoDB': C15_Pathogen-Geospatial-Analysis/04_cartodb.md
  - '第十六章 基因组分析实践':
    - '01. 细菌SNP溯源分析一': C16_Analysis_Examples/01_trace-Pae-from-different-source-by-SNP.md
    - '02. 细菌比较基因组学研究': C16_Analysis_Examples/02_comparative-analysis-Ban-genomes.md
use_directory_urls: true

extra_javascript:
  #- https://cdn.rawgit.com/knsv/mermaid/6.0.0/dist/mermaid.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/raphael/2.2.7/raphael.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.8.3/underscore-min.js
  - https://cdnjs.cloudflare.com/ajax/libs/js-sequence-diagrams/1.0.6/sequence-diagram-min.js
  - https://cdnjs.cloudflare.com/ajax/libs/flowchart/1.6.5/flowchart.min.js
  - assets/js/umlconvert.js

markdown_extensions:
  - codehilite
  - admonition
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.superfences

google_analytics: ['UA-55420348-3', 'auto']
