site_name: Pathogen NGS 数据分析入门
site_description: '病原微生物高通量测序数据分析手册'
site_author: 'Mark Renton'
site_url: 'https://indexofire.github.io/pathongs'
theme: 'material'
copyright: 'Copyright &copy; 2016 - 2018 HZCDC@Lab'

repo_url: https://github.com/indexofire/pathongs/

extra:
  palette:
    primary: 'light blue'

pages:
  - '前言': index.md
  - '第一章 背景知识介绍':
    - '01. Linux 系统操作基本命令': chapter_01/01_basic-cml.md
    - '02. Linux 安装实例': chapter_01/02_linux-installation.md
    - '03. Linux 系统管理': chapter_01/03_linux-administration.md
    - '04. 数据处理常用工具之 awk': chapter_01/04_awk.md
    - '05. 测序数据工具 bioawk': chapter_01/05_bioawk.md
    - '06. 了解 Python 生活轻松一点': chapter_01/06_python.md
    - '07. 生信分析要学一点 shell': chapter_01/07_shell.md
  - '第二章 序列处理':
    - '01. EMBOSS 工具集': chapter_02/01_emboss.md
    - '02. Blast 与 Blast+': chapter_02/02_blast.md
    - '03. 国产序列处理神器 SeqKit': chapter_02/08_seqkit.md
    - '04. K-mer 处理工具': chapter_02/09_kmer.md
  - '第三章 数据的上传和下载':
    - '01. 生物公共数据库': chapter_03/01_databases.md
    - '02. 生物数据文件格式': chapter_03/02_fileformat.md
    - '03. 玩转 edirect': chapter_03/03_edirect.md
    #- '3.1 MUMmer': chapter_03/mummer.md
    #- '3.2 C-Sibelia': chapter_03/c-sibelia.md
  - '第四章 基因组组装与比对':
    - '01. bwa samtools 比对分析流程': chapter_04/01_bwa-samtools-pipeline.md
    - '02. GATK 分析流程': chapter_04/02_gatk.md
    - '03. 细菌基因组组装': chapter_04/03_bacteria-assembly.md
    - '04. 病毒基因组组装': chapter_04/04_virus-assembly.md
  - '第五章 基因组序列注释':
    - '01. Prokka 快速注释': chapter_05/01_prokka.md
    - '02. 在线注释工具 rast': chapter_05/02_rast.md
    - '03. 注释工具 PGAAP': chapter_05/03_PGAAP.md
    - '04. SNP注释工具 snpEFF': chapter_05/04_snpEFF.md
  - '第六章 Pangenome 数据分析':
    - '01. Pangenome 概述': chapter_06/01_pangenome.md
    - '02. Get_Homologues 分析': chapter_06/02_get_homologues.md
    - '03. BPGA 分析': chapter_06/03_BPGA.md
    - '04. Roary 分析': chapter_06/04_roary.md
    - '05. panseq 分析': chapter_06/05_panseq.md
    - '06. Gubbins 分析': chapter_06/06_gubbins.md
    - '07. OrthMCL 分析': chapter_06/07_orthmcl.md
    - '08. ITEP 分析': chapter_06/08_ITEP.md
  - '第七章 宏基因组分析':
    - '01. 16s 菌群分析': chapter_07/01_16s.md
    - '02. WGS 宏基因组分析': chapter_07/02_shotgun.md
  - '第八章 可视化分析工具':
    - '01. igv 查看比对结果': chapter_08/01_igv.md
    - '02. BRIG 细菌比较基因组分析工具': chapter_08/02_BRIG.md
    - '03. circos 工具使用': chapter_08/03_circos.md
  - '第九章 分析工具部署方式':
    - '01. 基于 docker 镜像': chapter_09/01_docker.md
    - '02. Galaxy 平台': chapter_09/02_galaxy.md
    - '03. Amazon EC2 云平台': chapter_09/03_amazon.md
    - '04. 其他平台': chapter_09/04_others.md
  - '第十章 基因组分析实践':
    - '01. 铜绿假单胞菌不同来源株SNP溯源': chapter_10/01_trace-Pae-from-different-source-by-SNP.md
    - '02. 炭疽芽胞杆菌比较基因组学研究': chapter_10/02_comparative-analysis-Ban-genomes.md
  - '第十一章 常见分析工具':
    - '01. SRST2 短序列比对基因工具': chapter_11/01_srst2.md
    - '02. 拼接序列管家基因扫描工具 MLST': chapter_11/02_mlst.md
    - '03. 拼接序列耐药基因扫描工具 Ariba': chapter_11/03_ariba.md
    - '04. 细菌共线性分析工具 C-Sibelia': chapter_11/04_csibelia.md
use_directory_urls: true

extra_javascript:
  #- https://cdn.rawgit.com/knsv/mermaid/6.0.0/dist/mermaid.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/raphael/2.2.7/raphael.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.8.3/underscore-min.js
  - https://cdnjs.cloudflare.com/ajax/libs/js-sequence-diagrams/1.0.6/sequence-diagram-min.js
  - https://cdnjs.cloudflare.com/ajax/libs/flowchart/1.6.5/flowchart.min.js
  - assets/js/umlconvert.js

markdown_extensions:
  - codehilite
  - admonition
  - footnotes
  - meta
  - toc(permalink=true)
  - pymdownx.arithmatex
  - pymdownx.betterem(smart_enable=all)
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tasklist(custom_checkbox=true)
  - pymdownx.tilde
  - pymdownx.superfences

google_analytics: ['UA-55420348-3', 'auto']
